package Modelo;
// Generated 19-oct-2017 9:10:41 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Solicitud generated by hbm2java
 */
public class Solicitud  implements java.io.Serializable {


     private Integer idSolicitud;
     private Usuario usuario;
     private Date fechaIngreso;
     private String nombre;
     private String apellido;
     private String region;
     private String localidad;
     private String telefono;
     private String email;
     private String rut;
     private String origen;
     private String estado;

    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }



    public Solicitud() {
    }

	
    public Solicitud(Usuario usuario) {
        this.usuario = usuario;
    }
    public Solicitud(Usuario usuario, Date fechaIngreso, String nombre, String apellido, String region, String localidad, String telefono, String email, String rut, String origen) {
       this.usuario = usuario;
       this.fechaIngreso = fechaIngreso;
       this.nombre = nombre;
       this.apellido = apellido;
       this.region = region;
       this.localidad = localidad;
       this.telefono = telefono;
       this.email = email;
       this.rut = rut;
       this.origen = origen;
    }
   
    public Integer getIdSolicitud() {
        return this.idSolicitud;
    }
    
    public void setIdSolicitud(Integer idSolicitud) {
        this.idSolicitud = idSolicitud;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getRut() {
        return this.rut;
    }
    
    public void setRut(String rut) {
        this.rut = rut;
    }
    public String getOrigen() {
        return this.origen;
    }
    
    public void setOrigen(String origen) {
        this.origen = origen;
    }




}


