/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import Code.NewHibernateUtil;
import Modelo.Usuario;
import javax.swing.JOptionPane;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import Modelo.*;

/**
 *
 * @author Pepe
 */
public class CambioSolicitud extends javax.swing.JFrame {

    int idsolicitud;
    Solicitud solicitud;
    AdminClientConsult cc;
    Usuario usuario;

    /**
     * Creates new form CambioSolicitud
     */
    public CambioSolicitud(int id, AdminClientConsult cc, Usuario usuario) {
        initComponents();
        this.idsolicitud = id;
        this.cc = cc;
        this.usuario = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        cb_status = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cb_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nuevo", "Reprogramada", "No contesta" }));
        cb_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_statusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(cb_status, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(cb_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(jButton1)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SessionFactory main = NewHibernateUtil.getSessionFactory();
        Session session;
        //        apertura sesion hibernate
        session = main.openSession();
//        Query, con parametro nick particular igual a->formUser
        Query query = session.createQuery("FROM Solicitud s WHERE s.idSolicitud=:id");
        query.setParameter("id", idsolicitud);
//        Extracción de objeto usuario desde la DB (se puede extraer lista con query.list();
        solicitud = (Solicitud) query.uniqueResult();
        session.close();
        if (solicitud == null) {
            JOptionPane.showMessageDialog(this, "Error al procesar el dato");
        } else {
            solicitud.setEstado(cb_status.getSelectedItem().toString());
            System.out.println(solicitud.getEstado() + " id = " + solicitud.getIdSolicitud());
            usuario.updateSolicitud(solicitud);
            cc.startTable();
            this.dispose();
        }

        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cb_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_statusActionPerformed

    /**
     * @param args the command line arguments
     *
     *
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_status;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
